# Generated by Django 2.1.1 on 2018-09-08 20:08

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256, verbose_name='Message Topic')),
                ('rw', models.IntegerField(default=1,
                                           validators=[django.core.validators.MaxValueValidator(2),
                                                       django.core.validators.MinValueValidator(0)],
                                           verbose_name='Read Write Mode')),
                ('is_enabled', models.BooleanField(default=False,
                                                   verbose_name='ACL Enabled')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'access_list',
                'verbose_name_plural': 'access_list',
                'db_table': 'access_list',
            },
        ),
        migrations.CreateModel(
            name='CustomerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=32, verbose_name='Device Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'customer_device',
                'verbose_name_plural': 'customer_device',
                'db_table': 'customer_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('model', models.CharField(max_length=32, primary_key=True,
                                           serialize=False, verbose_name='Device Model Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'device_model',
                'verbose_name_plural': 'device_model',
                'db_table': 'device_model',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.CharField(max_length=32, primary_key=True,
                                               serialize=False, verbose_name='Device Id')),
                ('password', models.CharField(max_length=128, verbose_name='Password')),
                ('super', models.BooleanField(default=False,)),
                ('is_enabled', models.BooleanField(default=False,)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('last_update_date', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Connected From')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                            to='nalkinscloud_mosquitto.DeviceModel')),
            ],
            options={
                'verbose_name': 'device',
                'verbose_name_plural': 'devices',
                'db_table': 'devices',
            },
        ),
        migrations.CreateModel(
            name='DeviceType',
            fields=[
                ('type', models.CharField(max_length=32, primary_key=True,
                                          serialize=False, verbose_name='Device Type Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
            ],
            options={
                'verbose_name': 'device_type',
                'verbose_name_plural': 'device_type',
                'db_table': 'device_type',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=256, verbose_name='Message Topic')),
                ('message', models.CharField(max_length=256, verbose_name='Message Body')),
                ('qos', models.IntegerField(default=1,
                                            validators=[django.core.validators.MaxValueValidator(1),
                                                        django.core.validators.MinValueValidator(0)],
                                            verbose_name='QOS')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                             to='nalkinscloud_mosquitto.Device')),
            ],
            options={
                'verbose_name': 'messages',
                'verbose_name_plural': 'messages',
                'db_table': 'messages',
            },
        ),
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='nalkinscloud_mosquitto.DeviceType'),
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='device_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='nalkinscloud_mosquitto.Device'),
        ),
        migrations.AddField(
            model_name='customerdevice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accesslist',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                       to='nalkinscloud_mosquitto.Device'),
        ),
        migrations.AlterUniqueTogether(
            name='accesslist',
            unique_together={('device', 'topic')},
        ),
    ]
