# Generated by Django 2.0.1 on 2018-01-16 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nalkinscloud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailverification',
            old_name='user_id',
            new_name='user',
        ),
    ]
